// Champion data mapping - in production, this would be fetched from Data Dragon API
export const CHAMPION_DATA: Record<number, { key: string; name: string; title: string }> = {
  266: { key: "Aatrox", name: "Aatrox", title: "the Darkin Blade" },
  103: { key: "Ahri", name: "Ahri", title: "the Nine-Tailed Fox" },
  84: { key: "Akali", name: "Akali", title: "the Rogue Assassin" },
  166: { key: "Akshan", name: "Akshan", title: "the Rogue Sentinel" },
  12: { key: "Alistar", name: "Alistar", title: "the Minotaur" },
  32: { key: "Amumu", name: "Amumu", title: "the Sad Mummy" },
  34: { key: "Anivia", name: "Anivia", title: "the Cryophoenix" },
  1: { key: "Annie", name: "Annie", title: "the Dark Child" },
  523: { key: "Aphelios", name: "Aphelios", title: "the Weapon of the Faithful" },
  22: { key: "Ashe", name: "Ashe", title: "the Frost Archer" },
  136: { key: "AurelionSol", name: "Aurelion Sol", title: "The Star Forger" },
  268: { key: "Azir", name: "Azir", title: "the Emperor of the Sands" },
  432: { key: "Bard", name: "Bard", title: "the Wandering Caretaker" },
  200: { key: "Belveth", name: "Bel'Veth", title: "the Void Empress" },
  53: { key: "Blitzcrank", name: "Blitzcrank", title: "the Great Steam Golem" },
  63: { key: "Brand", name: "Brand", title: "the Burning Vengeance" },
  201: { key: "Braum", name: "Braum", title: "the Heart of the Freljord" },
  233: { key: "Briar", name: "Briar", title: "the Restrained Hunger" },
  51: { key: "Caitlyn", name: "Caitlyn", title: "the Sheriff of Piltover" },
  164: { key: "Camille", name: "Camille", title: "the Steel Shadow" },
  69: { key: "Cassiopeia", name: "Cassiopeia", title: "the Serpent's Embrace" },
  31: { key: "Chogath", name: "Cho'Gath", title: "the Terror of the Void" },
  42: { key: "Corki", name: "Corki", title: "the Daring Bombardier" },
  122: { key: "Darius", name: "Darius", title: "the Hand of Noxus" },
  131: { key: "Diana", name: "Diana", title: "Scorn of the Moon" },
  119: { key: "Draven", name: "Draven", title: "the Glorious Executioner" },
  36: { key: "DrMundo", name: "Dr. Mundo", title: "the Madman of Zaun" },
  245: { key: "Ekko", name: "Ekko", title: "the Boy Who Shattered Time" },
  60: { key: "Elise", name: "Elise", title: "the Spider Queen" },
  28: { key: "Evelynn", name: "Evelynn", title: "Agony's Embrace" },
  81: { key: "Ezreal", name: "Ezreal", title: "the Prodigal Explorer" },
  9: { key: "Fiddlesticks", name: "Fiddlesticks", title: "the Ancient Fear" },
  114: { key: "Fiora", name: "Fiora", title: "the Grand Duelist" },
  105: { key: "Fizz", name: "Fizz", title: "the Tidal Trickster" },
  3: { key: "Galio", name: "Galio", title: "the Colossus" },
  41: { key: "Gangplank", name: "Gangplank", title: "the Saltwater Scourge" },
  86: { key: "Garen", name: "Garen", title: "The Might of Demacia" },
  150: { key: "Gnar", name: "Gnar", title: "the Missing Link" },
  79: { key: "Gragas", name: "Gragas", title: "the Rabble Rouser" },
  104: { key: "Graves", name: "Graves", title: "the Outlaw" },
  887: { key: "Gwen", name: "Gwen", title: "The Hallowed Seamstress" },
  120: { key: "Hecarim", name: "Hecarim", title: "the Shadow of War" },
  74: { key: "Heimerdinger", name: "Heimerdinger", title: "the Revered Inventor" },
  420: { key: "Illaoi", name: "Illaoi", title: "the Kraken Priestess" },
  39: { key: "Irelia", name: "Irelia", title: "the Blade Dancer" },
  427: { key: "Ivern", name: "Ivern", title: "the Green Father" },
  40: { key: "Janna", name: "Janna", title: "the Storm's Fury" },
  59: { key: "JarvanIV", name: "Jarvan IV", title: "the Exemplar of Demacia" },
  24: { key: "Jax", name: "Jax", title: "Grandmaster at Arms" },
  126: { key: "Jayce", name: "Jayce", title: "the Defender of Tomorrow" },
  202: { key: "Jhin", name: "Jhin", title: "the Virtuoso" },
  222: { key: "Jinx", name: "Jinx", title: "the Loose Cannon" },
  145: { key: "Kaisa", name: "Kai'Sa", title: "Daughter of the Void" },
  429: { key: "Kalista", name: "Kalista", title: "the Spear of Vengeance" },
  43: { key: "Karma", name: "Karma", title: "the Enlightened One" },
  30: { key: "Karthus", name: "Karthus", title: "the Deathsinger" },
  38: { key: "Kassadin", name: "Kassadin", title: "the Void Walker" },
  55: { key: "Katarina", name: "Katarina", title: "the Sinister Blade" },
  10: { key: "Kayle", name: "Kayle", title: "the Righteous" },
  141: { key: "Kayn", name: "Kayn", title: "the Shadow Reaper" },
  85: { key: "Kennen", name: "Kennen", title: "the Heart of the Tempest" },
  121: { key: "Khazix", name: "Kha'Zix", title: "the Voidreaver" },
  203: { key: "Kindred", name: "Kindred", title: "The Eternal Hunters" },
  240: { key: "Kled", name: "Kled", title: "the Cantankerous Cavalier" },
  96: { key: "KogMaw", name: "Kog'Maw", title: "the Mouth of the Abyss" },
  897: { key: "KSante", name: "K'Sante", title: "The Pride of Nazumah" },
  7: { key: "Leblanc", name: "LeBlanc", title: "the Deceiver" },
  64: { key: "LeeSin", name: "Lee Sin", title: "the Blind Monk" },
  89: { key: "Leona", name: "Leona", title: "the Radiant Dawn" },
  876: { key: "Lillia", name: "Lillia", title: "the Bashful Bloom" },
  127: { key: "Lissandra", name: "Lissandra", title: "the Ice Witch" },
  236: { key: "Lucian", name: "Lucian", title: "the Purifier" },
  117: { key: "Lulu", name: "Lulu", title: "the Fae Sorceress" },
  99: { key: "Lux", name: "Lux", title: "the Lady of Luminosity" },
  54: { key: "Malphite", name: "Malphite", title: "Shard of the Monolith" },
  90: { key: "Malzahar", name: "Malzahar", title: "the Prophet of the Void" },
  57: { key: "Maokai", name: "Maokai", title: "the Twisted Treant" },
  11: { key: "MasterYi", name: "Master Yi", title: "the Wuju Bladesman" },
  902: { key: "Milio", name: "Milio", title: "The Gentle Flame" },
  21: { key: "MissFortune", name: "Miss Fortune", title: "the Bounty Hunter" },
  62: { key: "MonkeyKing", name: "Wukong", title: "the Monkey King" },
  82: { key: "Mordekaiser", name: "Mordekaiser", title: "the Iron Revenant" },
  25: { key: "Morgana", name: "Morgana", title: "the Fallen" },
  950: { key: "Naafiri", name: "Naafiri", title: "the Hound of a Hundred Bites" },
  267: { key: "Nami", name: "Nami", title: "the Tidecaller" },
  75: { key: "Nasus", name: "Nasus", title: "the Curator of the Sands" },
  111: { key: "Nautilus", name: "Nautilus", title: "the Titan of the Depths" },
  518: { key: "Neeko", name: "Neeko", title: "the Curious Chameleon" },
  76: { key: "Nidalee", name: "Nidalee", title: "the Bestial Huntress" },
  895: { key: "Nilah", name: "Nilah", title: "the Joy Unbound" },
  56: { key: "Nocturne", name: "Nocturne", title: "the Eternal Nightmare" },
  20: { key: "Nunu", name: "Nunu & Willump", title: "the Boy and His Yeti" },
  2: { key: "Olaf", name: "Olaf", title: "the Berserker" },
  61: { key: "Orianna", name: "Orianna", title: "the Lady of Clockwork" },
  516: { key: "Ornn", name: "Ornn", title: "The Fire below the Mountain" },
  80: { key: "Pantheon", name: "Pantheon", title: "the Unbreakable Spear" },
  78: { key: "Poppy", name: "Poppy", title: "Keeper of the Hammer" },
  555: { key: "Pyke", name: "Pyke", title: "the Bloodharbor Ripper" },
  246: { key: "Qiyana", name: "Qiyana", title: "Empress of the Elements" },
  133: { key: "Quinn", name: "Quinn", title: "Demacia's Wings" },
  497: { key: "Rakan", name: "Rakan", title: "The Charmer" },
  33: { key: "Rammus", name: "Rammus", title: "the Armordillo" },
  421: { key: "RekSai", name: "Rek'Sai", title: "the Void Burrower" },
  526: { key: "Rell", name: "Rell", title: "the Iron Maiden" },
  888: { key: "Renata", name: "Renata Glasc", title: "the Chem-Baroness" },
  58: { key: "Renekton", name: "Renekton", title: "the Butcher of the Sands" },
  107: { key: "Rengar", name: "Rengar", title: "the Pridestalker" },
  92: { key: "Riven", name: "Riven", title: "the Exile" },
  68: { key: "Rumble", name: "Rumble", title: "the Mechanized Menace" },
  13: { key: "Ryze", name: "Ryze", title: "the Rune Mage" },
  360: { key: "Samira", name: "Samira", title: "the Desert Rose" },
  113: { key: "Sejuani", name: "Sejuani", title: "Fury of the North" },
  235: { key: "Senna", name: "Senna", title: "the Redeemer" },
  147: { key: "Seraphine", name: "Seraphine", title: "the Starry-Eyed Songstress" },
  875: { key: "Sett", name: "Sett", title: "the Boss" },
  35: { key: "Shaco", name: "Shaco", title: "the Demon Jester" },
  98: { key: "Shen", name: "Shen", title: "the Eye of Twilight" },
  102: { key: "Shyvana", name: "Shyvana", title: "the Half-Dragon" },
  27: { key: "Singed", name: "Singed", title: "the Mad Chemist" },
  14: { key: "Sion", name: "Sion", title: "The Undead Juggernaut" },
  15: { key: "Sivir", name: "Sivir", title: "the Battle Mistress" },
  72: { key: "Skarner", name: "Skarner", title: "the Crystal Vanguard" },
  901: { key: "Smolder", name: "Smolder", title: "the Fiery Fledgling" },
  37: { key: "Sona", name: "Sona", title: "Maven of the Strings" },
  16: { key: "Soraka", name: "Soraka", title: "the Starchild" },
  50: { key: "Swain", name: "Swain", title: "the Noxian Grand General" },
  517: { key: "Sylas", name: "Sylas", title: "the Unshackled" },
  134: { key: "Syndra", name: "Syndra", title: "the Dark Sovereign" },
  223: { key: "TahmKench", name: "Tahm Kench", title: "The River King" },
  163: { key: "Taliyah", name: "Taliyah", title: "the Stoneweaver" },
  91: { key: "Talon", name: "Talon", title: "the Blade's Shadow" },
  44: { key: "Taric", name: "Taric", title: "the Shield of Valoran" },
  17: { key: "Teemo", name: "Teemo", title: "the Swift Scout" },
  412: { key: "Thresh", name: "Thresh", title: "the Chain Warden" },
  18: { key: "Tristana", name: "Tristana", title: "the Yordle Gunner" },
  48: { key: "Trundle", name: "Trundle", title: "the Troll King" },
  23: { key: "Tryndamere", name: "Tryndamere", title: "the Barbarian King" },
  4: { key: "TwistedFate", name: "Twisted Fate", title: "the Card Master" },
  29: { key: "Twitch", name: "Twitch", title: "the Plague Rat" },
  77: { key: "Udyr", name: "Udyr", title: "the Spirit Walker" },
  6: { key: "Urgot", name: "Urgot", title: "the Dreadnought" },
  110: { key: "Varus", name: "Varus", title: "the Arrow of Retribution" },
  67: { key: "Vayne", name: "Vayne", title: "the Night Hunter" },
  45: { key: "Veigar", name: "Veigar", title: "the Tiny Master of Evil" },
  161: { key: "Velkoz", name: "Vel'Koz", title: "the Eye of the Void" },
  711: { key: "Vex", name: "Vex", title: "the Gloomist" },
  254: { key: "Vi", name: "Vi", title: "the Piltover Enforcer" },
  234: { key: "Viego", name: "Viego", title: "The Ruined King" },
  112: { key: "Viktor", name: "Viktor", title: "the Machine Herald" },
  8: { key: "Vladimir", name: "Vladimir", title: "the Crimson Reaper" },
  106: { key: "Volibear", name: "Volibear", title: "the Relentless Storm" },
  19: { key: "Warwick", name: "Warwick", title: "the Uncaged Wrath of Zaun" },
  498: { key: "Xayah", name: "Xayah", title: "the Rebel" },
  101: { key: "Xerath", name: "Xerath", title: "the Magus Ascendant" },
  5: { key: "XinZhao", name: "Xin Zhao", title: "the Seneschal of Demacia" },
  157: { key: "Yasuo", name: "Yasuo", title: "the Unforgiven" },
  777: { key: "Yone", name: "Yone", title: "the Unforgotten" },
  83: { key: "Yorick", name: "Yorick", title: "Shepherd of Souls" },
  350: { key: "Yuumi", name: "Yuumi", title: "the Magical Cat" },
  154: { key: "Zac", name: "Zac", title: "the Secret Weapon" },
  238: { key: "Zed", name: "Zed", title: "the Master of Shadows" },
  221: { key: "Zeri", name: "Zeri", title: "The Spark of Zaun" },
  115: { key: "Ziggs", name: "Ziggs", title: "the Hexplosives Expert" },
  26: { key: "Zilean", name: "Zilean", title: "the Chronokeeper" },
  142: { key: "Zoe", name: "Zoe", title: "the Aspect of Twilight" },
  143: { key: "Zyra", name: "Zyra", title: "Rise of the Thorns" }
};

export function getChampionById(id: number) {
  return CHAMPION_DATA[id] || { key: "Unknown", name: "Unknown", title: "Unknown Champion" };
}